# First_Set.py
# Source: SeaStack Language FIRST SETS
# lambda (epsilon) is represented as None

FIRST = {
    "<program>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", "AHOY"],
    "<global-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", None],
    "<var-arr-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<coin-tail>": ["=", ",", "!!", "{", "("],
    "<coin-dec>": ["=", ",", "!!", "{"],
    "<coin-init>": ["=", None],
    "<coin-mult>": [",", None],
    "<coin-init-val>": ["id", "(", "COIN-lit"],
    "<coin-val>": ["id", "(", "COIN-lit"],
    "<coin-ope>": ["id", "(", "COIN-lit"],
    "<coin-exp>": ["+", "-", "*", "/", "%", "^", None],
    "<arith-op>": ["+", "-", "*", "/", "%", "^"],
    "<coin-arr>": ["{"],
    
    "<coin-arr-tail>": ["=", "{", None],
    "<coin-arr1>": ["id", "(", "COIN-lit"],
    "<coin-arr-val>": ["id", "(", "COIN-lit"],
    "<cav-tail>": [",", None],
    "<coin-arr2-tail>": ["=", None],
    "<coin-arr2>": ["["],
    "<cav2-tail>": [",", None],
    "<coin-func>": ["("],

    "<dime-tail>": ["=", ",", "!!", "{", "("],
    "<dime-dec>": ["=", ",", "!!", "{"],
    "<dime-init>": ["=", None], 
    "<dime-mult>": [",", None], 
    "<dime-init-val>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<dime-val>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<dime-ope>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<digits>": ["COIN-lit", "DIME-lit"],
    "<dime-exp>": ["+", "-", "*", "/", "%", "^", None],
    "<dime-arr>": ["{"],
    "<dime-arr-tail>": ["=", "{", None],
    "<dime-arr1>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<dime-arr-val>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<dav-tail>": [",", None],
    "<dime-arr2-tail>": ["=", None],
    "<dime-arr2>": ["["],
    "<dav2-tail>": [",", None],
    "<dime-func>": ["("],

    "<parch-tail>": ["=", ",", "!!", "{", "("],
    "<parch-dec>": ["=", ",", "!!", "{"],
    "<parch-init>": ["=", None],
    "<parch-mult>": [",", None],
    "<parch-init-val>": ["id", "PARCH-lit"],
    "<parch-val>": ["id", "PARCH-lit"],
    "<parch-arr>": ["{"],
    "<parch-arr-tail>": ["=", "{", None],
    "<parch-arr1>": ["id", "PARCH-lit"],
    "<parch-arr-val>": ["id", "PARCH-lit"],
    "<pav-tail>": [",", None],
    "<parch-arr2-tail>": ["=", None],
    "<parch-arr2>": ["["],
    "<pav2-tail>": [",", None],
    "<parch-func>": ["("],
    
    "<scroll-tail>": ["=", ",", "!!", "{", "("],
    "<scroll-dec>": ["=", ",", "!!", "{"],
    "<scroll-init>": ["=", None],
    "<scroll-mult>": [",", None],
    "<scroll-init-val>": ["id", "(", "SCROLL-lit"],
    "<scroll-val>": ["id", "(", "SCROLL-lit"],
    "<scroll-ope>": ["id", "(", "SCROLL-lit"],
    "<scr-char>": ["{", None],
    "<index>": ["id", "COIN-lit"],
    "<scroll-exp>": ["&", None],
    "<concat-op>": ["&"],
    "<scroll-arr>": ["{"],
    "<scroll-arr-tail>": ["=", "{", None],
    "<scroll-arr1>": ["id", "(", "SCROLL-lit"],
    "<scroll-arr-val>": ["id", "(", "SCROLL-lit"],
    "<sav-tail>": [",", None],
    "<scroll-arr2-tail>": ["=", None],
    "<scroll-arr2>": ["["],
    "<sav2-tail>": [",", None],
    "<scroll-func>": ["("],

    "<bool-tail>": ["=", ",", "!!", "{", "("],
    "<bool-dec>": ["=", ",", "!!", "{"],
    "<bool-init>": ["=", None],
    "<bool-mult>": [",", None],
    "<bool-init-val>": ["id", "(", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<bool-val>": ["id", "(", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<bool-ope>": ["id", "(", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<bool>": ["AYE", "NAY", "!", "!#"],
    "<bool-lit>": ["AYE", "NAY"],
    "<not-op>": ["!", "!#"],
    "<not-val>": ["id", "(", "AYE", "NAY"],
    "<log-tail>": ["==", "!=", None],
    "<bool-digit>": ["COIN-lit", "DIME-lit"],
    "<bool-arith>": ["+", "-", "*", "/", "%", "^", None],
    "<arith>": ["+", "-", "*", "/", "%", "^"],
    
    "<arel-ope>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<rel-eq>": ["<", ">", "<=", ">=", "==", "!="],
    "<rel>": ["<", ">", "<=", ">="],
    "<rel-op>": ["<", ">", "<=", ">="],
    "<rel-tail>": ["==", "!=", None],
    "<eq-op>": ["==", "!="],

    "<bool-parch>": ["id", "PARCH-lit"],
    "<scroll>": ["SCROLL-lit"],
    "<bool-scroll>": ["id", "(", "SCROLL-lit"],
    "<bool-concat>": ["&", None],
    "<concat>": ["&"],
    "<bool-exp2>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "==", "!=", "&", None],
    "<concat-tail>": ["==", "!="],
    "<eq-ope>": ["id", "(", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#"],
    "<bool-exp3>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "^&"],
    "<bool-rel>": ["<", ">", "<=", ">=", None],
    "<bool-exp>": ["||", "&&", None],

    "<log-op>": ["||", "&&"],
    "<bool-arr>": ["{"],
    "<bool-arr-tail>": ["=", "{", None],
    "<bool-arr1>": ["id", "(",  "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<bav-tail>": [",", None],
    "<bool-arr-val>": ["id", "(",  "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<bool-arr2-tail>": ["=", None],
    "<bool-arr2>": ["["],
    "<bav2-tail>": [",", None],
    "<bool-func>": ["("],
    
    "<params>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<param-mult>": [",", None],

    "<d-type>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<ret-stmts>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<coin-retval>": ["id", "(", "COIN-lit"],
    "<dime-retval>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<parch-retval>": ["id", "PARCH-lit"],
    "<scroll-retval>": ["id", "(", "SCROLL-lit"],
    "<bool-retval>": ["id", "(",  "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],

    "<id-tail>": ["{", "$", "(", None],
    "<elmt>": ["{"],
    "<elmt-tail>": ["{", None],
    "<mem>": ["$"],
    "<func>": ["("],
   
    "<args>": ["id", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", None],
    "<args-val>": ["id", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<args-mult>": [",", None],
    "<var-val>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#"],
    "<value>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#"],
    
    "<var-digit>": ["COIN-lit", "DIME-lit"],
    "<digit-tail>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "==", "!=", None],
    "<var-arith>": ["+", "-", "*", "/", "%", "^", None],
    "<var-releq>": ["<", ">", "<=", ">=", "==", "!=", None],
    "<var-rel>": ["<", ">", "<=", ">=", None],
    "<var-logeq>": ["||", "&&", "==", "!=", None],
    "<logeq-op>": ["||", "&&", "==", "!="],
    "<var-log>": ["||", "&&", None],
    "<log-ope>": ["id", "(", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],

    "<eq-parch>": ["==", "!=", None],
    "<eq-scroll>": ["==", "!=", None],
    "<var-scroll>": ["&", None],
    "<concat-ope>": ["id", "(", "SCROLL-lit"],
    "<var-bool>": ["AYE", "NAY", "!", "!#"],

    "<var-exp>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", None],
    "<expressions>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&"],
    "<const>": ["LOCKE"],
    "<const-init>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],

    "<coin-locke>": ["id"],
    "<coin-locke-mult>": [",", None],
    "<dime-locke>": ["id"],
    "<locke-digit>": ["COIN-lit", "DIME-lit"],
    "<dime-locke-mult>": [",", None],
    
    "<parch-locke>": ["id"],
    "<parch-locke-mult>": [",", None],
    
    "<scroll-locke>": ["id"],
    "<scr-id>": ["{", None],
    "<scroll-locke-mult>": [",", None],

    "<bool-locke>": ["id"],
    "<locke-bool>": ["AYE", "NAY"],
    "<bool-locke-mult>": [",", None],
    "<struct>": ["MAST", None],
 
    "<mem-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<mem-mult>": [",", None],
    "<mem-dec-tail>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", None],
    
    "<sub-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", None],
    "<return-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<nonreturn-func>": ["ABYSS"],
    "<nonret-stmnts>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<nonret-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<nonret-back>": ["BACK", None],
    
    "<local-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "MAST", None],
    "<var-arr>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<coin-local>": ["=", ",", "!!", "{"],
    "<dime-local>": ["=", ",", "!!", "{"],
    "<parch-local>": ["=", ",", "!!", "{"],
    "<scroll-local>": ["=", ",", "!!", "{"],
    "<bool-local>": ["=", ",", "!!", "{"],

    "<struct-dec>": ["MAST", None],
    "<str-dec-init>": [",", "=", None],
    "<str-dec-tail>": [",", None],

    "<str-val>": ["id", "$", "COIN-lit", "DIME-lit", "PARCH-lit", "AYE", "NAY", "!", "!#"],
    "<str-val-tail>": [",", None],

    "<ahoy-stmnts>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<ahoy-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<statements>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<stmnt-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    
    "<assign-stmnt>": ["id"],
    "<assign-tail>": ["{", "$", "=", "+=", "-=", "*=", "/=", "%=", "^=", "("],
    "<arr-str>": ["{", "$", None],
    "<elmt-tail2>": ["{", None],
    "<assign-body>": ["=", "+=", "-=", "*=", "/=", "%=", "^="],
    "<assign-val>": ["id", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<arith-assign-op>": ["+=", "-=", "*=", "/=", "%=", "^="],
    "<arith-ope>": ["id", "(", "COIN-lit", "DIME-lit"],
    "<arith-tail>": ["+", "-", "*", "/", "%", "^", None],
    
    "<ask-stmnt>": ["ASK"],
    "<addr>": ["@"],
    "<id-addr>": ["{", "$", None],
    "<addr-tail>": [",", None],
    
    "<echo-stmnt>": ["ECHO"],
    "<echo-arg>": [",", None],
    "<echo-val>": ["id", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],

    "<look-stmnt>": ["LOOK"],
    "<condition>": ["id", "(", "AYE", "NAY", "!", "!#", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit"],
    "<look-body>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<jump-stmnt>": ["SAIL", "LAND", None],
    "<look-tail>": ["DROPLOOK", "DROP", None],
    
    "<chart-stmnt>": ["CHART"],
    "<chart-cond>": ["COIN-lit", "PARCH-lit", "id"],
    "<chart-const>": ["COIN-lit", "PARCH-lit"],
    
    "<courses>": ["COURSE"],
    "<course-body>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<course-jmp>": ["SAIL", "LAND", None],
    "<course-tail>": ["COURSE", None],
    
    "<adrift-case>": ["ADRIFT", None],
    "<adrift-body>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<hoist-stmnt>": ["HOIST"],

    "<init>": ["COIN", "id", None],
    "<id-init>": ["{", "$"],
    "<init1>": [",", None],
    "<init2>": [",", None],
    
    "<hoist-cond>": ["id"],
    "<id-cond>": ["{", "$"],
    "<releq-op>": ["<", ">", "<=", ">=", "==", "!="],
    "<hoist-ope>": ["COIN-lit", "id"],
    "<hoist-log>": ["||", "&&", None],
    "<inc-dec>": ["id", "+#", "-#"],
    "<in-de>": ["id", "+#", "-#"],
    "<in-de2>": [",", None],

    "<heave-stmnt>": ["HEAVE"],
    "<haul-stmnt>": ["HAUL"],
    "<unary-exp>": ["+#", "-#"],
    "<unary-op>": ["+#", "-#"],
}