# First_Set.py
# Source: SeaStack Language Specification - VIII. FIRST SET
# lambda (epsilon) is represented as None

FIRST = {
    "<program>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "LOCKE", "MAST", "AHOY"],
    "<global-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "LOCKE", "MAST", None],
    "<d-type>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<dtype-tail>": ["=", ",", "{", "(", "!!"],
    "<var-arr-dec>": ["=", ",", "{", "!!"],
    "<variable>": ["=", ",", "!!"],
    "<var-init>": ["=", None],
    "<multi-var-init>": [",", None],
    "<array>": ["{"],
    "<arr-tail>": ["{", "=", None],
    "<arr-val>": ["id", "-", "COIN-lit", "DIME-lit", "SCROLL-lit", "PARCH-lit", "AYE", "NAY", "(", "!", "!#"],
    "<arr-val-tail>": [",", None],
    "<arr2-tail>": ["=", None],
    "<arr2-val>": ["[", "!!"], # Note: '!!' inferred from empty tail in some contexts, but table says '['
    "<arr2-val-tail>": [",", None],
    "<locke-dec>": ["LOCKE"],
    "<struct-def>": ["MAST", None],
    "<mem-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<mem-dec-tail>": [",", "!!"],
    "<more-mem>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", None],
    "<expression>": ["(", "id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#"],
    "<operands>": ["(", "id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#"],
    "<value>": ["id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY"],
    "<id-tail>": ["$", "(", "{", None],
    "<arr-elmt>": ["{"],
    "<arr-index>": ["COIN-lit", "id"],
    "<arr-elmt-tail>": ["{", None],
    "<str-mem>": ["$"],
    "<func-args>": ["(", None],
    "<args>": ["id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", None],
    "<args-tail>": [",", None],
    "<literals>": ["-", "COIN-lit", "DIME-lit", "SCROLL-lit", "PARCH-lit", "AYE", "NAY"],
    "<digits>": ["-", "COIN-lit", "DIME-lit"],
    "<neg>": ["-", None],
    "<coin-dime>": ["COIN-lit", "DIME-lit"],
    "<bool-lit>": ["AYE", "NAY"],
    "<arr-str>": ["{", "$", None],
    "<exp-tail>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", None],
    "<gen-exp>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", None],
    "<arith>": ["+", "-", "*", "/", "%", "^", None],
    "<arith-exp>": ["+", "-", "*", "/", "%", "^"],
    "<arith-op>": ["+", "-", "*", "/", "%", "^"],
    "<gen-ope>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<bool>": ["AYE", "NAY", "!", "!#"],
    "<not>": ["!", "!#"],
    "<not-val>": ["id", "AYE", "NAY", "("],
    "<rel>": ["<", ">", "<=", ">=", None],
    "<rel-op>": ["<", ">", "<=", ">="],
    "<logeq>": ["||", "&&", "==", "!=", None],
    "<logeq-op>": ["||", "&&", "==", "!="],
    "<log_op>": ["||", "&&"],
    "<equal-op>": ["==", "!="],
    "<scroll>": ["&", None],
    "<scroll-ope>": ["SCROLL-lit", "id", "("],
    "<sub-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", None],
    "<return-func>": ["("],
    "<func-parameters>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", None],
    "<func-tail>": [",", None],
    "<back-val>": ["id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "("],
    "<nonreturn-func>": ["ABYSS"],
    "<nonreturn-back>": ["BACK", None],
    "<local-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "MAST", None],
    "<loc-dec-tail>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "MAST", None],
    "<struct>": ["MAST", None],
    "<struct-dec>": ["MAST"],
    "<struct-dec-init>": ["=", None],
    "<struct-dec-tail>": [",", None],
    "<statements>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<stmnt-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<assign-stmnt>": ["id"],
    "<assign-tail>": ["{", "$", "(", "=", "+=", "-=", "*=", "/=", "%=", "^="],
    "<assign-body>": ["=", "+=", "-=", "*=", "/=", "%=", "^="],
    "<assign-val>": ["(", "id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#", "["],
    "<arr-assign>": ["(", "id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#", "["],
    "<arith-assign-op>": ["+=", "-=", "*=", "/=", "%=", "^="],
    "<ask-stmnt>": ["ASK"],
    "<addr>": ["@"],
    "<addr-tail>": [",", None],
    "<echo-stmnt>": ["ECHO"],
    "<echo-arg>": ["(", "id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#", None],
    "<echo-arg-tail>": [",", None],
    "<look-stmnt>": ["LOOK"],
    "<cond-exp>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<sail-stmt>": ["SAIL", None],
    "<look-tail>": ["DROPLOOK", "DROP", None],
    "<chart-stmnt>": ["CHART"],
    "<chart-cond>": ["id", "-", "COIN-lit", "PARCH-lit"],
    "<const>": ["-", "COIN-lit", "PARCH-lit"],
    "<courses>": ["COURSE"],
    "<course-tail>": ["COURSE", None],
    "<adrift-case>": ["ADRIFT", None],
    "<hoist-stmnt>": ["HOIST"],
    "<init>": ["id", "COIN", None],
    "<heave-stmnt>": ["HEAVE"],
    "<haul-stmnt>": ["HAUL"],
    "<unary-exp>": ["+#", "-#"],
    "<unary-op>": ["+#", "-#"]
}