# First_Set.py
# Source: SeaStack Language Specification - FIRST SET (UPDATED)
# lambda (epsilon) is represented as None

FIRST = {
    "<program>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", "AHOY"],
    "<global-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", None],
    "<d-type>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<dtype-tail>": ["=", ",", "{", "(", "!!"],
    "<var-arr-dec>": ["=", ",", "{", "!!"],
    "<variable>": ["=", ",", "!!"],
    "<var-init>": ["=", None],
    "<multi-var-init>": [",", None],
    "<array>": ["{"],
    "<arr-tail>": ["{", "=", None],
    "<arr-val>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#"],
    "<arr-val-tail>": [",", None],
    "<arr2-tail>": ["=", None],
    "<arr2-val>": ["["],
    "<arr2-val-tail>": [",", None],
    "<locke-dec>": ["LOCKE"],
    "<locke-init>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<scr-id>": ["{", None],
    "<struct-def>": ["MAST", None],
    "<mem-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL"],
    "<mem-dec-tail>": [",", None],
    "<more-mem>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", None],
    
    # Expressions & Values
    "<var-val>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#"],
    "<operands>": ["id", "("],
    "<id-tail>": ["{", "$", "(", None],
    "<arr-elmt>": ["{"],
    "<arr-index>": ["id", "COIN-lit"],
    "<arr-elmt-tail>": ["{", None],
    "<str-mem>": ["$"],
    "<func-args>": ["("],
    "<args>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#", None],
    "<literals>": ["COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY"],
    "<digits>": ["COIN-lit", "DIME-lit"],
    "<bool-lit>": ["AYE", "NAY"],
    "<scroll>": ["SCROLL-lit"],
    "<exp-tail>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", None],
    "<digit-tail>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "==", "!=", None],
    
    # Arithmetic & Logic
    "<arith-exp>": ["+", "-", "*", "/", "%", "^"],
    "<arith>": ["+", "-", "*", "/", "%", "^"],
    "<arith-tail>": ["+", "-", "*", "/", "%", "^", None],
    "<arith-op>": ["+", "-", "*", "/", "%", "^"],
    "<arel-ope>": ["id", "COIN-lit", "DIME-lit", "("],
    "<rel-exp>": ["<", ">", "<=", ">="],
    "<rel>": ["<", ">", "<=", ">="],
    "<rel-op>": ["<", ">", "<=", ">="],
    "<rel-eq>": ["<", ">", "<=", ">=", "==", "!=", None],
    "<rel-eq-exp>": ["<", ">", "<=", ">=", "==", "!="],
    "<eq-arith>": ["==", "!="],
    "<eq-op>": ["==", "!="],
    "<log-eq>": ["||", "&&", "==", "!=", None],
    "<log-exp>": ["||", "&&", None],
    "<log-op>": ["||", "&&"],
    "<log-ope>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#"],
    "<eq-exp>": ["==", "!="],
    "<not>": ["!", "!#"],
    "<not-val>": ["id", "AYE", "NAY", "("],
    
    # Scroll / Strings
    "<scroll-tail>": ["&", "==", "!=", None],
    "<scroll-exp>": ["&"],
    "<concat>": ["&"],
    "<concat-tail>": ["&", None],
    "<scroll-ope>": ["id", "SCROLL-lit", "("],
    "<eq-scroll>": ["==", "!=", None],
    "<eq-parch>": ["==", "!=", None],
    
    # Functions
    "<sub-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", None],
    "<return-func>": ["("],
    "<func-params>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", None],
    "<func-tail>": [","],
    "<nonreturn-func>": ["ABYSS"],
    "<nonreturn-back>": ["BACK", None],
    
    # Structures & Locals
    "<local-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "MAST", None],
    "<struct>": ["MAST", None],
    "<str-dec>": ["MAST"],
    "<str-dec-init>": [",", "=", None],
    "<str-dec-tail>": [",", None],
    "<str-val>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#", "$"],
    "<str-val-tail>": [",", None],
    
    # Statements
    "<statements>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<stmnt-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", None],
    "<assign-stmnt>": ["id"],
    "<assign-tail>": ["{", "$", "(", "=", "+=", "-=", "*=", "/=", "%=", "^="],
    "<arr-str>": ["{", "$", None],
    "<assign-body>": ["=", "+=", "-=", "*=", "/=", "%=", "^="],
    "<assign-val>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#", "["],
    "<arr-assign>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#", "["],
    "<arith-assign-op>": ["+=", "-=", "*=", "/=", "%=", "^="],
    
    # Specific Statements
    "<ask-stmnt>": ["ASK"],
    "<addr>": ["@"],
    "<addr-tail>": [",", None],
    "<echo-stmnt>": ["ECHO"],
    "<echo-arg>": [",", None],
    "<look-stmnt>": ["LOOK"],
    "<cond-exp>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#"],
    "<jump-stmnt>": ["SAIL", "LAND", None],
    "<look-tail>": ["DROPLOOK", "DROP", None],
    "<chart-stmnt>": ["CHART"],
    "<chart-cond>": ["id", "COIN-lit", "PARCH-lit"],
    "<const>": ["COIN-lit", "PARCH-lit"],
    "<courses>": ["COURSE"],
    "<course-tail>": ["COURSE", None],
    "<adrift-case>": ["ADRIFT", None],
    "<hoist-stmnt>": ["HOIST"],
    "<init>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "id", None],
    "<init1>": [",", None],
    "<init2>": [",", None],
    "<inc-dec>": ["+#", "-#", "id"],
    "<in-de>": ["+#", "-#", "id"],
    "<in-de2>": [",", None],
    "<heave-stmnt>": ["HEAVE"],
    "<haul-stmnt>": ["HAUL"],
    "<unary-exp>": ["+#", "-#"],
    "<unary-op>": ["+#", "-#"]
}