# Follow_Set.py
# Source: SeaStack Language Specification - FOLLOW SET (UPDATED)
# EOF represents the End of File ($)

FOLLOW = {
    "<program>": ["EOF"],
    "<global-dec>": ["AHOY"],
    "<d-type>": ["id"],
    "<dtype-tail>": ["AHOY"],
    "<var-arr-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", "AHOY"],
    "<variable>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", "AHOY"],
    "<var-init>": [",", "!!"],
    "<multi-var-init>": ["!!"],
    "<array>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", "AHOY"],
    "<arr-tail>": ["!!"],
    "<arr-val>": ["]", ")"],
    "<arr-val-tail>": ["]", ")"],
    "<arr2-tail>": ["!!"],
    "<arr2-val>": ["]", ","],
    "<arr2-val-tail>": ["]", ","],
    "<locke-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "LOCKE", "MAST", "ABYSS", "AHOY"],
    "<locke-init>": ["!!"],
    "<scr-id>": ["!!"],
    "<struct-def>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "AHOY"],
    "<mem-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "]"],
    "<mem-dec-tail>": ["!!"],
    "<more-mem>": ["]"],
    
    # Expressions
    "<var-val>": [",", "!!", ")", "]"],
    "<operands>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<id-tail>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<arr-elmt>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<arr-index>": ["}"],
    "<arr-elmt-tail>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<str-mem>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<func-args>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<args>": [")"],
    "<literals>": [",", "!!", ")", "]"],
    "<digits>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<bool-lit>": [",", "||", "&&", "==", "!=", "!!", ")", "]"],
    
    # Logic & Math
    "<scroll>": ["&", ",", "!!", ")", "==", "!=", "||", "&&"],
    "<exp-tail>": [",", "!!", ")", "]"],
    "<digit-tail>": [",", "!!", ")", "]"],
    "<arith-exp>": [",", "!!", ")", "]"],
    "<arith>": ["<", ">", "<=", ">=", "||", "&&", "==", "!=", ",", "!!", ")", "]"],
    "<arith-tail>": ["<", ">", "<=", ">=", "||", "&&", "==", "!=", ",", "!!", ")", "]"],
    "<arith-op>": ["id", "COIN-lit", "DIME-lit", "("],
    "<arel-ope>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", "]", ")"],
    "<rel-exp>": [",", "!!", ")", "]"],
    "<rel>": ["||", "&&", "==", "!="],
    "<rel-op>": ["id", "COIN-lit", "DIME-lit", "("],
    "<rel-eq>": [",", "!!", ")", "]"],
    "<rel-eq-exp>": [",", "!!", ")", "]"],
    "<eq-arith>": [",", "!!", ")", "]"],
    "<eq-op>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#"],
    "<log-eq>": [",", "!!", ")", "]"],
    "<log-exp>": [",", "!!", ")", "]"],
    "<log-op>": ["id", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "(", "!", "!#"],
    "<log-ope>": [",", "!!", ")", "]"],
    "<eq-exp>": [",", "!!", ")", "]"],
    "<not>": ["id", "AYE", "NAY", "("],
    "<not-val>": [",", "||", "&&", "==", "!=", "!!", ")", "]"],
    
    # Scroll
    "<scroll-tail>": [",", "!!", ")", "]"],
    "<scroll-exp>": [",", "!!", ")", "]"],
    "<concat>": ["==", "!=", "||", "&&", ",", "!!", ")", "]"],
    "<concat-tail>": ["==", "!=", "||", "&&", ",", "!!", ")", "]"],
    "<scroll-ope>": [",", "!!", ")", "]"],
    "<eq-scroll>": [",", "!!", ")", "]"],
    "<eq-parch>": [",", "!!", ")", "]"],
    
    # Functions & Decs
    "<sub-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "AHOY"],
    "<return-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "AHOY"],
    "<func-params>": [")"],
    "<func-tail>": [")"],
    "<nonreturn-func>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "AHOY"],
    "<nonreturn-back>": ["]"],
    "<local-dec>": ["BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<struct>": ["BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<str-dec>": ["MAST", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<str-dec-init>": ["!!"],
    "<str-dec-tail>": ["!!"],
    "<str-val>": [",", "]"],
    "<str-val-tail>": ["]"],
    
    # Statements
    "<statements>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<stmnt-tail>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<assign-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<assign-tail>": ["!!"],
    "<arr-str>": ["=", "+=", "-=", "*=", "/=", "%=", "^=", ",", ")"],
    "<assign-body>": ["!!"],
    "<assign-val>": ["!!"],
    "<arr-assign>": ["]"],
    "<arith-assign-op>": ["id", "COIN-lit", "DIME-lit", "("],
    "<ask-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<addr>": [")"],
    "<addr-tail>": [")"],
    "<echo-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<echo-arg>": [")"],
    "<look-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<cond-exp>": [")", "!!"],
    "<jump-stmnt>": ["COURSE", "ADRIFT", "]"],
    "<look-tail>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#"],
    "<chart-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<chart-cond>": [")"],
    "<const>": [":", ")"],
    "<courses>": ["COURSE", "ADRIFT", "]"],
    "<course-tail>": ["ADRIFT", "]"],
    "<adrift-case>": ["]"],
    "<hoist-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<init>": ["!!"],
    "<init1>": ["!!"],
    "<init2>": ["!!"],
    "<inc-dec>": [")"],
    "<in-de>": [",", ")"],
    "<in-de2>": [")"],
    "<heave-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<haul-stmnt>": ["]", "BACK", "id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "+#", "-#", "LAND", "SAIL", "COURSE", "ADRIFT"],
    "<unary-exp>": ["!!", ",", ")"],
    "<unary-op>": ["id"]
}