# Follow_Set.py
# Source: SeaStack Language Specification - IX. FOLLOW SET
# EOF represents the End of File ($)

FOLLOW = {
    "<program>": ["EOF"],
    "<global-dec>": ["AHOY"],
    "<d-type>": ["id"],
    "<dtype-tail>": ["AHOY"],
    "<var-arr-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "LOCKE", "MAST"],
    "<variable>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "LOCKE", "MAST"],
    "<var-init>": [",", "!!"],
    "<multi-var-init>": ["!!"],
    "<array>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "LOCKE", "MAST"],
    "<arr-tail>": ["!!"],
    "<arr-val>": ["]"],
    "<arr-val-tail>": ["]"],
    "<arr2-tail>": ["!!"],
    "<arr2-val>": ["]", ","],
    "<arr2-val-tail>": ["]", ","],
    "<locke-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "ABYSS", "LOCKE", "MAST"],
    "<struct-def>": ["COIN", "DIME", "ABYSS", "AHOY"],
    "<mem-dec>": ["COIN", "DIME", "PARCH", "SCROLL", "BOOL", "]"],
    "<mem-dec-tail>": ["!!"],
    "<more-mem>": ["]"],
    "<var-val>": [",", "!!", "]", ")"],
    "<expression>": [",", "!!", "]", ")"],
    "<operands>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<value>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<id-tail>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<arr-elmt>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<arr-index>": ["}"],
    "<arr-elmt-tail>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<str-mem>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<func-args>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<args>": [")"],
    "<args-tail>": [")"],
    "<literals>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<digits>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<neg>": ["COIN-lit", "DIME-lit"],
    "<coin-dime>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<bool-lit>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<arr-str>": [",", "+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", "&", "!!", ")", "]"],
    "<exp-tail>": [",", "!!", "]", ")"],
    "<gen-exp>": [",", "!!", "]", ")"],
    "<arith>": ["<", ">", "<=", ">=", "||", "&&", "==", "!=", ",", "!!", ")", "]"],
    "<arith-exp>": ["<", ">", "<=", ">=", "||", "&&", "==", "!=", ",", "!!", ")", "]"],
    "<arith-op>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<gen-ope>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", ")"],
    "<bool>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", ")"],
    "<not>": ["id", "AYE", "NAY", "("],
    "<not-val>": ["+", "-", "*", "/", "%", "^", "<", ">", "<=", ">=", "||", "&&", "==", "!=", ",", "!!", ")", "]"],
    "<rel>": ["||", "&&", "==", "!=", ",", "!!", ")", "]"],
    "<rel-op>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<logeq>": [",", "!!", "]", ")"],
    "<logeq-op>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<log_op>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<equal-op>": ["id", "-", "COIN-lit", "DIME-lit", "AYE", "NAY", "!", "!#", "("],
    "<scroll>": [",", "!!", "]", ")"],
    "<scroll-ope>": [",", "!!", "]", ")"],
    "<sub-func>": ["COIN", "DIME", "ABYSS", "AHOY"],
    "<return-func>": ["COIN", "DIME", "ABYSS", "AHOY"],
    "<func-parameters>": [")"],
    "<func-tail>": [")"],
    "<back-val>": ["!!"],
    "<nonreturn-func>": ["COIN", "DIME", "ABYSS", "AHOY"],
    "<nonreturn-back>": ["]"],
    "<local-dec>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#"],
    "<loc-dec-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#"],
    "<struct>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#"],
    "<struct-dec>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "MAST"],
    "<struct-dec-init>": ["!!"],
    "<struct-dec-tail>": ["!!"],
    "<statements>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<stmnt-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<assign-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<assign-tail>": ["!!"],
    "<assign-body>": ["!!"],
    "<assign-val>": ["!!"],
    "<arr-assign>": ["]"],
    "<arith-assign-op>": ["(", "id", "-", "COIN-lit", "DIME-lit", "PARCH-lit", "SCROLL-lit", "AYE", "NAY", "!", "!#"],
    "<ask-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<addr>": [")"],
    "<addr-tail>": [")"],
    "<echo-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<echo-arg>": [")"],
    "<echo-arg-tail>": [")"],
    "<look-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<cond-exp>": [")", "!!"],
    "<sail-stmt>": ["]"],
    "<look-tail>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<chart-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<chart-cond>": [")"],
    "<const>": [")", ":"],
    "<courses>": ["COURSE", "ADRIFT", "]"],
    "<course-tail>": ["ADRIFT", "]"],
    "<adrift-case>": ["]"],
    "<hoist-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<init>": ["!!"],
    "<heave-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<haul-stmnt>": ["id", "ASK", "ECHO", "LOOK", "CHART", "HOIST", "HEAVE", "HAUL", "SAIL", "+#", "-#", "BACK", "]", "LAND"],
    "<unary-exp>": ["!!", ")"],
    "<unary-op>": ["id"]
}