import sys
from syntax.predict_set import PREDICT
from backend.error_msg import ErrorHandler

# ============================================================
# AUTO-GENERATED by generate_syn_parser.py
# Do NOT edit manually — edit the grammar TSV and regenerate.
# ============================================================


class Parser:
    def __init__(self, tokens, source_code):
        ignored_types = [
            "whitespace",
            "newline",
            "single-comment",
            "multi-comment",
        ]

        self.tokens = [t for t in tokens if t.type not in ignored_types]

        for t in self.tokens:
            if t.type.startswith("id") and t.type[2:].isdigit():
                t.type = "id"

        self.pos = 0
        self.current_token = self.tokens[self.pos] if self.tokens else None
        self.errors = []
        self.err_handler = ErrorHandler(source_code)

    # =========================================
    # Utility Methods
    # =========================================
    def advance(self):
        """Moves to the next token."""
        self.pos += 1
        if self.pos < len(self.tokens):
            self.current_token = self.tokens[self.pos]
        else:
            self.current_token = None

    def eat(self, token_type):
        if self.current_token and self.current_token.type == token_type:
            self.advance()
        else:
            raise Exception(self.err_handler.get_missing_token_error(
                self.current_token,
                token_type,
            ))

    def get_production(self, non_terminal):
        if not self.current_token:
            return None
        productions = PREDICT.get(non_terminal, {})
        return productions.get(self.current_token.type)

    def error_invalid_token(self, non_terminal):
        expected = list(PREDICT.get(non_terminal, {}).keys())
        raise Exception(self.err_handler.get_invalid_token_error(self.current_token, expected))

    def error_invalid_token_ctx(self, expected):
        """Raise an invalid-token error using a caller-supplied expected-token list.

        Used by nullable non-terminals when their caller provides the FIRST set
        of the production suffix that follows the nullable call — giving a precise,
        context-aware "expected ..." message instead of the generic PREDICT-based one.
        """
        raise Exception(self.err_handler.get_invalid_token_error(
            self.current_token, list(expected)))

    # =========================================
    # Entry Point
    # =========================================
    def parse(self):
        try:
            if not self.tokens:
                raise Exception(self.err_handler.get_missing_start_error())

            self.program()

            if self.current_token is not None:
                raise Exception(self.err_handler.get_expected_eof_error(self.current_token))

        except Exception as e:
            if e.args and isinstance(e.args[0], dict):
                self.errors.append(e.args[0])
            else:
                self.errors.append({
                    "type": "Parser Crash",
                    "line": "?",
                    "col": "?",
                    "found": "CRASH",
                    "expected": [],
                    "message": str(e),
                })

        return self.errors

    # =========================================
    # GRAMMAR PRODUCTIONS
    # =========================================

    def program(self):
        # <program>
        prod = self.get_production('<program>')
        if prod == 1:
            self.global_dec(_ctx_expected=('AHOY',))
            self.eat('AHOY')
            self.eat('(')
            self.eat(')')
            self.eat('[')
            self.ahoy_local_dec(_ctx_expected=('+#', '-#', 'ASK', 'CHART', 'ECHO', 'HAUL', 'HEAVE', 'HOIST', 'LOOK', 'id'))
            self.ahoy_stmnts()
            self.eat(']')
        else:
            self.error_invalid_token('<program>')

    def global_dec(self, _ctx_expected=()):
        # <global-dec>
        prod = self.get_production('<global-dec>')
        if prod == 2:
            self.var_arr_func()
        elif prod == 3:
            self.const()
            self.global_dec()
        elif prod == 4:
            self.struct(_ctx_expected=('ABYSS', 'BOOL', 'COIN', 'DIME', 'PARCH', 'SCROLL'))
            self.sub_func()
        elif prod == 5:
            self.nonreturn_func()
        elif prod == 6:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def var_arr_func(self):
        # <var-arr-func>
        prod = self.get_production('<var-arr-func>')
        if prod == 7:
            self.eat('COIN')
            self.eat('id')
            self.coin_dec()
        elif prod == 8:
            self.eat('DIME')
            self.eat('id')
            self.dime_dec()
        elif prod == 9:
            self.eat('PARCH')
            self.eat('id')
            self.parch_dec()
        elif prod == 10:
            self.eat('SCROLL')
            self.eat('id')
            self.scroll_dec()
        elif prod == 11:
            self.eat('BOOL')
            self.eat('id')
            self.bool_dec()
        else:
            self.error_invalid_token('<var-arr-func>')

    def coin_dec(self):
        # <coin-dec>
        prod = self.get_production('<coin-dec>')
        if prod == 12:
            self.coin_var_arr()
            self.eat('!!')
            self.global_dec()
        elif prod == 13:
            self.coin_func()
        else:
            self.error_invalid_token('<coin-dec>')

    def coin_var_arr(self):
        # <coin-var-arr>
        prod = self.get_production('<coin-var-arr>')
        if prod == 14:
            self.coin_var()
        elif prod == 15:
            self.coin_arr()
        else:
            self.error_invalid_token('<coin-var-arr>')

    def coin_var(self):
        # <coin-var>
        prod = self.get_production('<coin-var>')
        if prod == 16:
            self.coin_init(_ctx_expected=(',',))
            self.coin_init_mult()
        else:
            self.error_invalid_token('<coin-var>')

    def coin_init(self, _ctx_expected=()):
        # <coin-init>
        prod = self.get_production('<coin-init>')
        if prod == 17:
            self.eat('=')
            self.coin_val()
        elif prod == 18:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def coin_init_mult(self, _ctx_expected=()):
        # <coin-init-mult>
        prod = self.get_production('<coin-init-mult>')
        if prod == 19:
            self.eat(',')
            self.eat('id')
            self.coin_init(_ctx_expected=(',',))
            self.coin_init_mult()
        elif prod == 20:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def coin_val(self):
        # <coin-val>
        prod = self.get_production('<coin-val>')
        if prod == 21:
            self.coin_ope()
            self.coin_arith()
        else:
            self.error_invalid_token('<coin-val>')

    def coin_ope(self):
        # <coin-ope>
        prod = self.get_production('<coin-ope>')
        if prod == 22:
            self.eat('COIN-lit')
        elif prod == 23:
            self.neg(_ctx_expected=('(', 'id'))
            self.neg_coin_ope()
        else:
            self.error_invalid_token('<coin-ope>')

    def neg(self, _ctx_expected=()):
        # <neg>
        prod = self.get_production('<neg>')
        if prod == 24:
            self.eat('-')
        elif prod == 25:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def neg_coin_ope(self):
        # <neg-coin-ope>
        prod = self.get_production('<neg-coin-ope>')
        if prod == 26:
            self.eat('id')
            self.id_tail()
        elif prod == 27:
            self.eat('(')
            self.coin_val()
            self.eat(')')
        else:
            self.error_invalid_token('<neg-coin-ope>')

    def coin_arith(self, _ctx_expected=()):
        # <coin-arith>
        prod = self.get_production('<coin-arith>')
        if prod == 28:
            self.arith_op()
            self.coin_ope()
            self.coin_arith()
        elif prod == 29:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def arith_op(self):
        # <arith-op>
        prod = self.get_production('<arith-op>')
        if prod == 30:
            self.eat('+')
        elif prod == 31:
            self.eat('-')
        elif prod == 32:
            self.eat('*')
        elif prod == 33:
            self.eat('/')
        elif prod == 34:
            self.eat('%')
        elif prod == 35:
            self.eat('^')
        else:
            self.error_invalid_token('<arith-op>')

    def coin_arr(self):
        # <coin-arr>
        prod = self.get_production('<coin-arr>')
        if prod == 36:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.coin_arr_tail()
        else:
            self.error_invalid_token('<coin-arr>')

    def coin_arr_tail(self, _ctx_expected=()):
        # <coin-arr-tail>
        prod = self.get_production('<coin-arr-tail>')
        if prod == 37:
            self.eat('=')
            self.eat('[')
            self.coin_arr1()
            self.eat(']')
        elif prod == 38:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.coin_arr2_tail()
        elif prod == 39:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def coin_arr1(self):
        # <coin-arr1>
        prod = self.get_production('<coin-arr1>')
        if prod == 40:
            self.coin_val()
            self.cav_tail()
        else:
            self.error_invalid_token('<coin-arr1>')

    def cav_tail(self, _ctx_expected=()):
        # <cav-tail>
        prod = self.get_production('<cav-tail>')
        if prod == 41:
            self.eat(',')
            self.coin_arr1()
        elif prod == 42:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def coin_arr2_tail(self, _ctx_expected=()):
        # <coin-arr2-tail>
        prod = self.get_production('<coin-arr2-tail>')
        if prod == 43:
            self.eat('=')
            self.eat('[')
            self.coin_arr2()
            self.eat(']')
        elif prod == 44:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def coin_arr2(self):
        # <coin-arr2>
        prod = self.get_production('<coin-arr2>')
        if prod == 45:
            self.eat('[')
            self.coin_arr1()
            self.eat(']')
            self.cav2_tail()
        else:
            self.error_invalid_token('<coin-arr2>')

    def cav2_tail(self, _ctx_expected=()):
        # <cav2-tail>
        prod = self.get_production('<cav2-tail>')
        if prod == 46:
            self.eat(',')
            self.coin_arr2()
        elif prod == 47:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def coin_func(self):
        # <coin-func>
        prod = self.get_production('<coin-func>')
        if prod == 48:
            self.eat('(')
            self.params(_ctx_expected=(')',))
            self.eat(')')
            self.eat('[')
            self.local_dec(_ctx_expected=('+#', '-#', 'ASK', 'BACK', 'CHART', 'ECHO', 'HAUL', 'HEAVE', 'HOIST', 'LOOK', 'id'))
            self.ret_stmnts(_ctx_expected=('BACK',))
            self.eat('BACK')
            self.coin_val()
            self.eat('!!')
            self.eat(']')
            self.sub_func()
        else:
            self.error_invalid_token('<coin-func>')

    def dime_dec(self):
        # <dime-dec>
        prod = self.get_production('<dime-dec>')
        if prod == 49:
            self.dime_var_arr()
            self.eat('!!')
            self.global_dec()
        elif prod == 50:
            self.dime_func()
        else:
            self.error_invalid_token('<dime-dec>')

    def dime_var_arr(self):
        # <dime-var-arr>
        prod = self.get_production('<dime-var-arr>')
        if prod == 51:
            self.dime_var()
        elif prod == 52:
            self.dime_arr()
        else:
            self.error_invalid_token('<dime-var-arr>')

    def dime_var(self):
        # <dime-var>
        prod = self.get_production('<dime-var>')
        if prod == 53:
            self.dime_init(_ctx_expected=(',',))
            self.dime_init_mult()
        else:
            self.error_invalid_token('<dime-var>')

    def dime_init(self, _ctx_expected=()):
        # <dime-init>
        prod = self.get_production('<dime-init>')
        if prod == 54:
            self.eat('=')
            self.dime_val()
        elif prod == 55:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_init_mult(self, _ctx_expected=()):
        # <dime-init-mult>
        prod = self.get_production('<dime-init-mult>')
        if prod == 56:
            self.eat(',')
            self.eat('id')
            self.dime_init(_ctx_expected=(',',))
            self.dime_init_mult()
        elif prod == 57:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_val(self):
        # <dime-val>
        prod = self.get_production('<dime-val>')
        if prod == 58:
            self.dime_ope()
            self.dime_arith()
        else:
            self.error_invalid_token('<dime-val>')

    def dime_ope(self):
        # <dime-ope>
        prod = self.get_production('<dime-ope>')
        if prod == 59:
            self.eat('DIME-lit')
        elif prod == 60:
            self.eat('COIN-lit')
        elif prod == 61:
            self.neg(_ctx_expected=('(', 'id'))
            self.neg_dime_ope()
        else:
            self.error_invalid_token('<dime-ope>')

    def neg_dime_ope(self):
        # <neg-dime-ope>
        prod = self.get_production('<neg-dime-ope>')
        if prod == 62:
            self.eat('id')
            self.id_tail()
        elif prod == 63:
            self.eat('(')
            self.dime_val()
            self.eat(')')
        else:
            self.error_invalid_token('<neg-dime-ope>')

    def dime_arith(self, _ctx_expected=()):
        # <dime-arith>
        prod = self.get_production('<dime-arith>')
        if prod == 64:
            self.arith_op()
            self.dime_ope()
            self.dime_arith()
        elif prod == 65:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_arr(self):
        # <dime-arr>
        prod = self.get_production('<dime-arr>')
        if prod == 66:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.dime_arr_tail()
        else:
            self.error_invalid_token('<dime-arr>')

    def dime_arr_tail(self, _ctx_expected=()):
        # <dime-arr-tail>
        prod = self.get_production('<dime-arr-tail>')
        if prod == 67:
            self.eat('=')
            self.eat('[')
            self.dime_arr1()
            self.eat(']')
        elif prod == 68:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.dime_arr2_tail()
        elif prod == 69:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_arr1(self):
        # <dime-arr1>
        prod = self.get_production('<dime-arr1>')
        if prod == 70:
            self.dime_val()
            self.dav_tail()
        else:
            self.error_invalid_token('<dime-arr1>')

    def dav_tail(self, _ctx_expected=()):
        # <dav-tail>
        prod = self.get_production('<dav-tail>')
        if prod == 71:
            self.eat(',')
            self.dime_arr1()
        elif prod == 72:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_arr2_tail(self, _ctx_expected=()):
        # <dime-arr2-tail>
        prod = self.get_production('<dime-arr2-tail>')
        if prod == 73:
            self.eat('=')
            self.eat('[')
            self.dime_arr2()
            self.eat(']')
        elif prod == 74:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_arr2(self):
        # <dime-arr2>
        prod = self.get_production('<dime-arr2>')
        if prod == 75:
            self.eat('[')
            self.dime_arr1()
            self.eat(']')
            self.dav2_tail()
        else:
            self.error_invalid_token('<dime-arr2>')

    def dav2_tail(self, _ctx_expected=()):
        # <dav2-tail>
        prod = self.get_production('<dav2-tail>')
        if prod == 76:
            self.eat(',')
            self.dime_arr2()
        elif prod == 77:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_func(self):
        # <dime-func>
        prod = self.get_production('<dime-func>')
        if prod == 78:
            self.eat('(')
            self.params(_ctx_expected=(')',))
            self.eat(')')
            self.eat('[')
            self.local_dec(_ctx_expected=('+#', '-#', 'ASK', 'BACK', 'CHART', 'ECHO', 'HAUL', 'HEAVE', 'HOIST', 'LOOK', 'id'))
            self.ret_stmnts(_ctx_expected=('BACK',))
            self.eat('BACK')
            self.dime_val()
            self.eat('!!')
            self.eat(']')
            self.sub_func()
        else:
            self.error_invalid_token('<dime-func>')

    def parch_dec(self):
        # <parch-dec>
        prod = self.get_production('<parch-dec>')
        if prod == 79:
            self.parch_var_arr()
            self.eat('!!')
            self.global_dec()
        elif prod == 80:
            self.parch_func()
        else:
            self.error_invalid_token('<parch-dec>')

    def parch_var_arr(self):
        # <parch-var-arr>
        prod = self.get_production('<parch-var-arr>')
        if prod == 81:
            self.parch_var()
        elif prod == 82:
            self.parch_arr()
        else:
            self.error_invalid_token('<parch-var-arr>')

    def parch_var(self):
        # <parch-var>
        prod = self.get_production('<parch-var>')
        if prod == 83:
            self.parch_init(_ctx_expected=(',',))
            self.parch_init_mult()
        else:
            self.error_invalid_token('<parch-var>')

    def parch_init(self, _ctx_expected=()):
        # <parch-init>
        prod = self.get_production('<parch-init>')
        if prod == 84:
            self.eat('=')
            self.parch_val()
        elif prod == 85:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_init_mult(self, _ctx_expected=()):
        # <parch-init-mult>
        prod = self.get_production('<parch-init-mult>')
        if prod == 86:
            self.eat(',')
            self.eat('id')
            self.parch_init(_ctx_expected=(',',))
            self.parch_init_mult()
        elif prod == 87:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_val(self):
        # <parch-val>
        prod = self.get_production('<parch-val>')
        if prod == 88:
            self.eat('PARCH-lit')
        elif prod == 89:
            self.eat('id')
            self.id_tail()
        else:
            self.error_invalid_token('<parch-val>')

    def parch_arr(self):
        # <parch-arr>
        prod = self.get_production('<parch-arr>')
        if prod == 90:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.parch_arr_tail()
        else:
            self.error_invalid_token('<parch-arr>')

    def parch_arr_tail(self, _ctx_expected=()):
        # <parch-arr-tail>
        prod = self.get_production('<parch-arr-tail>')
        if prod == 91:
            self.eat('=')
            self.eat('[')
            self.parch_arr1()
            self.eat(']')
        elif prod == 92:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.parch_arr2_tail()
        elif prod == 93:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_arr1(self):
        # <parch-arr1>
        prod = self.get_production('<parch-arr1>')
        if prod == 94:
            self.parch_val()
            self.pav_tail()
        else:
            self.error_invalid_token('<parch-arr1>')

    def pav_tail(self, _ctx_expected=()):
        # <pav-tail>
        prod = self.get_production('<pav-tail>')
        if prod == 95:
            self.eat(',')
            self.parch_arr1()
        elif prod == 96:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_arr2_tail(self, _ctx_expected=()):
        # <parch-arr2-tail>
        prod = self.get_production('<parch-arr2-tail>')
        if prod == 97:
            self.eat('=')
            self.eat('[')
            self.parch_arr2()
            self.eat(']')
        elif prod == 98:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_arr2(self):
        # <parch-arr2>
        prod = self.get_production('<parch-arr2>')
        if prod == 99:
            self.eat('[')
            self.parch_arr1()
            self.eat(']')
            self.pav2_tail()
        else:
            self.error_invalid_token('<parch-arr2>')

    def pav2_tail(self, _ctx_expected=()):
        # <pav2-tail>
        prod = self.get_production('<pav2-tail>')
        if prod == 100:
            self.eat(',')
            self.parch_arr2()
        elif prod == 101:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_func(self):
        # <parch-func>
        prod = self.get_production('<parch-func>')
        if prod == 102:
            self.eat('(')
            self.params(_ctx_expected=(')',))
            self.eat(')')
            self.eat('[')
            self.local_dec(_ctx_expected=('+#', '-#', 'ASK', 'BACK', 'CHART', 'ECHO', 'HAUL', 'HEAVE', 'HOIST', 'LOOK', 'id'))
            self.ret_stmnts(_ctx_expected=('BACK',))
            self.eat('BACK')
            self.parch_val()
            self.eat('!!')
            self.eat(']')
            self.sub_func()
        else:
            self.error_invalid_token('<parch-func>')

    def scroll_dec(self):
        # <scroll-dec>
        prod = self.get_production('<scroll-dec>')
        if prod == 103:
            self.scroll_var_arr()
            self.eat('!!')
            self.global_dec()
        elif prod == 104:
            self.scroll_func()
            self.sub_func()
        else:
            self.error_invalid_token('<scroll-dec>')

    def scroll_var_arr(self):
        # <scroll-var-arr>
        prod = self.get_production('<scroll-var-arr>')
        if prod == 105:
            self.scroll_var()
        elif prod == 106:
            self.scroll_arr()
        else:
            self.error_invalid_token('<scroll-var-arr>')

    def scroll_var(self):
        # <scroll-var>
        prod = self.get_production('<scroll-var>')
        if prod == 107:
            self.scroll_init(_ctx_expected=(',',))
            self.scroll_init_mult()
        else:
            self.error_invalid_token('<scroll-var>')

    def scroll_init(self, _ctx_expected=()):
        # <scroll-init>
        prod = self.get_production('<scroll-init>')
        if prod == 108:
            self.eat('=')
            self.scroll_val()
        elif prod == 109:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_init_mult(self, _ctx_expected=()):
        # <scroll-init-mult>
        prod = self.get_production('<scroll-init-mult>')
        if prod == 110:
            self.eat(',')
            self.eat('id')
            self.scroll_init(_ctx_expected=(',',))
            self.scroll_init_mult()
        elif prod == 111:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_val(self):
        # <scroll-val>
        prod = self.get_production('<scroll-val>')
        if prod == 112:
            self.scroll_ope()
            self.scroll_concat()
        else:
            self.error_invalid_token('<scroll-val>')

    def scroll_ope(self):
        # <scroll-ope>
        prod = self.get_production('<scroll-ope>')
        if prod == 113:
            self.eat('SCROLL-lit')
            self.scr_char()
        elif prod == 114:
            self.eat('id')
            self.id_tail()
        elif prod == 115:
            self.eat('(')
            self.scroll_val()
            self.eat(')')
        else:
            self.error_invalid_token('<scroll-ope>')

    def scr_char(self, _ctx_expected=()):
        # <scr-char>
        prod = self.get_production('<scr-char>')
        if prod == 116:
            self.eat('{')
            self.index()
            self.eat('}')
        elif prod == 117:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def index(self):
        # <index>
        prod = self.get_production('<index>')
        if prod == 118:
            self.eat('COIN-lit')
        elif prod == 119:
            self.eat('id')
        else:
            self.error_invalid_token('<index>')

    def scroll_concat(self, _ctx_expected=()):
        # <scroll-concat>
        prod = self.get_production('<scroll-concat>')
        if prod == 120:
            self.eat('&')
            self.scroll_ope()
            self.scroll_concat()
        elif prod == 121:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_arr(self):
        # <scroll-arr>
        prod = self.get_production('<scroll-arr>')
        if prod == 122:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.scroll_arr_tail()
        else:
            self.error_invalid_token('<scroll-arr>')

    def scroll_arr_tail(self, _ctx_expected=()):
        # <scroll-arr-tail>
        prod = self.get_production('<scroll-arr-tail>')
        if prod == 123:
            self.eat('=')
            self.eat('[')
            self.scroll_arr1()
            self.eat(']')
        elif prod == 124:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.scroll_arr2_tail()
        elif prod == 125:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_arr1(self):
        # <scroll-arr1>
        prod = self.get_production('<scroll-arr1>')
        if prod == 126:
            self.scroll_val()
            self.sav_tail()
        else:
            self.error_invalid_token('<scroll-arr1>')

    def sav_tail(self, _ctx_expected=()):
        # <sav-tail>
        prod = self.get_production('<sav-tail>')
        if prod == 127:
            self.eat(',')
            self.scroll_arr1()
        elif prod == 128:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_arr2_tail(self, _ctx_expected=()):
        # <scroll-arr2-tail>
        prod = self.get_production('<scroll-arr2-tail>')
        if prod == 129:
            self.eat('=')
            self.eat('[')
            self.scroll_arr2()
            self.eat(']')
        elif prod == 130:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_arr2(self):
        # <scroll-arr2>
        prod = self.get_production('<scroll-arr2>')
        if prod == 131:
            self.eat('[')
            self.scroll_arr1()
            self.eat(']')
            self.sav2_tail()
        else:
            self.error_invalid_token('<scroll-arr2>')

    def sav2_tail(self, _ctx_expected=()):
        # <sav2-tail>
        prod = self.get_production('<sav2-tail>')
        if prod == 132:
            self.eat(',')
            self.scroll_arr2()
        elif prod == 133:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_func(self):
        # <scroll-func>
        prod = self.get_production('<scroll-func>')
        if prod == 134:
            self.eat('(')
            self.params(_ctx_expected=(')',))
            self.eat(')')
            self.eat('[')
            self.local_dec(_ctx_expected=('+#', '-#', 'ASK', 'BACK', 'CHART', 'ECHO', 'HAUL', 'HEAVE', 'HOIST', 'LOOK', 'id'))
            self.ret_stmnts(_ctx_expected=('BACK',))
            self.eat('BACK')
            self.scroll_val()
            self.eat('!!')
            self.eat(']')
            self.sub_func()
        else:
            self.error_invalid_token('<scroll-func>')

    def bool_dec(self):
        # <bool-dec>
        prod = self.get_production('<bool-dec>')
        if prod == 135:
            self.bool_var_arr()
            self.eat('!!')
            self.global_dec()
        elif prod == 136:
            self.bool_func()
        else:
            self.error_invalid_token('<bool-dec>')

    def bool_var_arr(self):
        # <bool-var-arr>
        prod = self.get_production('<bool-var-arr>')
        if prod == 137:
            self.bool_var()
        elif prod == 138:
            self.bool_arr()
        else:
            self.error_invalid_token('<bool-var-arr>')

    def bool_var(self):
        # <bool-var>
        prod = self.get_production('<bool-var>')
        if prod == 139:
            self.bool_init(_ctx_expected=(',',))
            self.bool_init_mult()
        else:
            self.error_invalid_token('<bool-var>')

    def bool_init(self, _ctx_expected=()):
        # <bool-init>
        prod = self.get_production('<bool-init>')
        if prod == 140:
            self.eat('=')
            self.bool_val()
        elif prod == 141:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_init_mult(self, _ctx_expected=()):
        # <bool-init-mult>
        prod = self.get_production('<bool-init-mult>')
        if prod == 142:
            self.eat(',')
            self.eat('id')
            self.bool_init(_ctx_expected=(',',))
            self.bool_init_mult()
        elif prod == 143:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_val(self):
        # <bool-val>
        prod = self.get_production('<bool-val>')
        if prod == 144:
            self.bool_ope()
            self.bool_exp()
        else:
            self.error_invalid_token('<bool-val>')

    def bool_ope(self):
        # <bool-ope>
        prod = self.get_production('<bool-ope>')
        if prod == 145:
            self.bool()
            self.bool_eq()
        elif prod == 146:
            self.eat('id')
            self.id_tail(_ctx_expected=('!=', '%', '*', '+', '-', '/', '<', '<=', '==', '>', '>=', '^'))
            self.bool_exp2()
        elif prod == 147:
            self.eat('(')
            self.value()
            self.eat(')')
            self.bool_exp2()
        elif prod == 148:
            self.digit()
            self.bool_arith(_ctx_expected=('!=', '<', '<=', '==', '>', '>='))
            self.rel_eq()
        elif prod == 149:
            self.eat('PARCH-lit')
            self.eq_op()
            self.parch_val()
        elif prod == 150:
            self.eat('SCROLL-lit')
            self.scr_char(_ctx_expected=('!=', '=='))
            self.eq_op()
            self.scroll_val()
        else:
            self.error_invalid_token('<bool-ope>')

    def bool(self):
        # <bool>
        prod = self.get_production('<bool>')
        if prod == 151:
            self.bool_lit()
        elif prod == 152:
            self.not_op()
            self.not_ope()
        else:
            self.error_invalid_token('<bool>')

    def bool_lit(self):
        # <bool-lit>
        prod = self.get_production('<bool-lit>')
        if prod == 153:
            self.eat('AYE')
        elif prod == 154:
            self.eat('NAY')
        else:
            self.error_invalid_token('<bool-lit>')

    def not_op(self):
        # <not-op>
        prod = self.get_production('<not-op>')
        if prod == 155:
            self.eat('!')
        elif prod == 156:
            self.eat('!#')
        else:
            self.error_invalid_token('<not-op>')

    def not_ope(self):
        # <not-ope>
        prod = self.get_production('<not-ope>')
        if prod == 157:
            self.eat('id')
            self.id_tail()
        elif prod == 158:
            self.eat('(')
            self.bool_val()
            self.eat(')')
        elif prod == 159:
            self.bool_lit()
        else:
            self.error_invalid_token('<not-ope>')

    def bool_eq(self, _ctx_expected=()):
        # <bool-eq>
        prod = self.get_production('<bool-eq>')
        if prod == 160:
            self.eq_op()
            self.bool_ope()
        elif prod == 161:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def digit(self):
        # <digit>
        prod = self.get_production('<digit>')
        if prod == 162:
            self.eat('COIN-lit')
        elif prod == 163:
            self.eat('DIME-lit')
        elif prod == 164:
            self.eat('-')
            self.neg_digit()
        else:
            self.error_invalid_token('<digit>')

    def neg_digit(self):
        # <neg-digit>
        prod = self.get_production('<neg-digit>')
        if prod == 165:
            self.eat('id')
            self.id_tail()
        elif prod == 166:
            self.eat('(')
            self.dime_val()
            self.eat(')')
        else:
            self.error_invalid_token('<neg-digit>')

    def bool_arith(self, _ctx_expected=()):
        # <bool-arith>
        prod = self.get_production('<bool-arith>')
        if prod == 167:
            self.arith_op()
            self.dime_ope()
            self.bool_arith()
        elif prod == 168:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def rel_eq(self):
        # <rel-eq>
        prod = self.get_production('<rel-eq>')
        if prod == 169:
            self.rel_op()
            self.dime_ope()
            self.bool_arith2(_ctx_expected=('!=', '=='))
            self.bool_eq()
        elif prod == 170:
            self.eq_op()
            self.dime_ope()
            self.bool_arith3()
        else:
            self.error_invalid_token('<rel-eq>')

    def rel_op(self):
        # <rel-op>
        prod = self.get_production('<rel-op>')
        if prod == 171:
            self.eat('<')
        elif prod == 172:
            self.eat('>')
        elif prod == 173:
            self.eat('<=')
        elif prod == 174:
            self.eat('>=')
        else:
            self.error_invalid_token('<rel-op>')

    def bool_arith2(self, _ctx_expected=()):
        # <bool-arith2>
        prod = self.get_production('<bool-arith2>')
        if prod == 175:
            self.arith_op()
            self.dime_ope()
            self.bool_arith2()
        elif prod == 176:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_arith3(self, _ctx_expected=()):
        # <bool-arith3>
        prod = self.get_production('<bool-arith3>')
        if prod == 177:
            self.arith_op()
            self.dime_ope()
            self.bool_arith3()
        elif prod == 178:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def eq_op(self):
        # <eq-op>
        prod = self.get_production('<eq-op>')
        if prod == 179:
            self.eat('==')
        elif prod == 180:
            self.eat('!=')
        else:
            self.error_invalid_token('<eq-op>')

    def bool_exp2(self, _ctx_expected=()):
        # <bool-exp2>
        prod = self.get_production('<bool-exp2>')
        if prod == 181:
            self.arith_op()
            self.dime_ope()
            self.bool_arith(_ctx_expected=('!=', '<', '<=', '==', '>', '>='))
            self.rel_eq()
        elif prod == 182:
            self.rel_op()
            self.dime_ope()
            self.bool_arith2(_ctx_expected=('!=', '=='))
            self.bool_eq()
        elif prod == 183:
            self.eq_op()
            self.eq_ope()
        elif prod == 184:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def eq_ope(self):
        # <eq-ope>
        prod = self.get_production('<eq-ope>')
        if prod == 185:
            self.eat('id')
            self.id_tail(_ctx_expected=('%', '*', '+', '-', '/', '<', '<=', '>', '>=', '^'))
            self.bool_exp3()
        elif prod == 186:
            self.eat('(')
            self.value()
            self.eat(')')
            self.bool_exp3()
        elif prod == 187:
            self.digit()
            self.bool_arith4(_ctx_expected=('<', '<=', '>', '>='))
            self.bool_rel()
        elif prod == 188:
            self.eat('PARCH-lit')
        elif prod == 189:
            self.eat('SCROLL-lit')
            self.scr_char()
        elif prod == 190:
            self.bool()
        else:
            self.error_invalid_token('<eq-ope>')

    def bool_arith4(self, _ctx_expected=()):
        # <bool-arith4>
        prod = self.get_production('<bool-arith4>')
        if prod == 191:
            self.arith_op()
            self.dime_ope()
            self.bool_arith4()
        elif prod == 192:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_rel(self, _ctx_expected=()):
        # <bool-rel>
        prod = self.get_production('<bool-rel>')
        if prod == 193:
            self.rel_op()
            self.dime_ope()
            self.bool_arith3()
        elif prod == 194:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_exp3(self, _ctx_expected=()):
        # <bool-exp3>
        prod = self.get_production('<bool-exp3>')
        if prod == 195:
            self.arith_op()
            self.bool_arith4(_ctx_expected=('<', '<=', '>', '>='))
            self.bool_rel()
        elif prod == 196:
            self.rel_op()
            self.dime_ope()
            self.bool_arith3()
        elif prod == 197:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_exp(self, _ctx_expected=()):
        # <bool-exp>
        prod = self.get_production('<bool-exp>')
        if prod == 198:
            self.log_op()
            self.bool_ope()
            self.bool_exp()
        elif prod == 199:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def log_op(self):
        # <log-op>
        prod = self.get_production('<log-op>')
        if prod == 200:
            self.eat('||')
        elif prod == 201:
            self.eat('&&')
        else:
            self.error_invalid_token('<log-op>')

    def bool_arr(self):
        # <bool-arr>
        prod = self.get_production('<bool-arr>')
        if prod == 202:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.bool_arr_tail()
        else:
            self.error_invalid_token('<bool-arr>')

    def bool_arr_tail(self, _ctx_expected=()):
        # <bool-arr-tail>
        prod = self.get_production('<bool-arr-tail>')
        if prod == 203:
            self.eat('=')
            self.eat('[')
            self.bool_arr1()
            self.eat(']')
        elif prod == 204:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
            self.bool_arr2_tail()
        elif prod == 205:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_arr1(self):
        # <bool-arr1>
        prod = self.get_production('<bool-arr1>')
        if prod == 206:
            self.bool_val()
            self.bav_tail()
        else:
            self.error_invalid_token('<bool-arr1>')

    def bav_tail(self, _ctx_expected=()):
        # <bav-tail>
        prod = self.get_production('<bav-tail>')
        if prod == 207:
            self.eat(',')
            self.bool_arr1()
        elif prod == 208:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_arr2_tail(self, _ctx_expected=()):
        # <bool-arr2-tail>
        prod = self.get_production('<bool-arr2-tail>')
        if prod == 209:
            self.eat('=')
            self.eat('[')
            self.bool_arr2()
            self.eat(']')
        elif prod == 210:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_arr2(self):
        # <bool-arr2>
        prod = self.get_production('<bool-arr2>')
        if prod == 211:
            self.eat('[')
            self.bool_arr1()
            self.eat(']')
            self.bav2_tail()
        else:
            self.error_invalid_token('<bool-arr2>')

    def bav2_tail(self, _ctx_expected=()):
        # <bav2-tail>
        prod = self.get_production('<bav2-tail>')
        if prod == 212:
            self.eat(',')
            self.bool_arr2()
        elif prod == 213:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_func(self):
        # <bool-func>
        prod = self.get_production('<bool-func>')
        if prod == 214:
            self.eat('(')
            self.params(_ctx_expected=(')',))
            self.eat(')')
            self.eat('[')
            self.local_dec()
            self.stmnts()
            self.eat('BACK')
            self.bool_val()
            self.eat('!!')
            self.eat(']')
            self.sub_func()
        else:
            self.error_invalid_token('<bool-func>')

    def params(self, _ctx_expected=()):
        # <params>
        prod = self.get_production('<params>')
        if prod == 215:
            self.d_type()
            self.eat('id')
            self.param_mult()
        elif prod == 216:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def param_mult(self, _ctx_expected=()):
        # <param-mult>
        prod = self.get_production('<param-mult>')
        if prod == 217:
            self.eat(',')
            self.params()
        elif prod == 218:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def d_type(self):
        # <d-type>
        prod = self.get_production('<d-type>')
        if prod == 219:
            self.eat('COIN')
        elif prod == 220:
            self.eat('DIME')
        elif prod == 221:
            self.eat('PARCH')
        elif prod == 222:
            self.eat('SCROLL')
        elif prod == 223:
            self.eat('BOOL')
        else:
            self.error_invalid_token('<d-type>')

    def ret_stmnts(self, _ctx_expected=()):
        # <ret-stmnts>
        prod = self.get_production('<ret-stmnts>')
        if prod == 224:
            self.statements()
            self.ret_stmnts()
        elif prod == 225:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def id_tail(self, _ctx_expected=()):
        # <id-tail>
        prod = self.get_production('<id-tail>')
        if prod == 226:
            self.eat('{')
            self.index()
            self.eat('}')
            self.elmt2()
        elif prod == 227:
            self.eat('$')
            self.eat('id')
        elif prod == 228:
            self.eat('(')
            self.args(_ctx_expected=(')',))
            self.eat(')')
        elif prod == 229:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def elmt2(self, _ctx_expected=()):
        # <elmt2>
        prod = self.get_production('<elmt2>')
        if prod == 230:
            self.eat('{')
            self.index()
            self.eat('}')
        elif prod == 231:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def mem(self):
        # <mem>
        prod = self.get_production('<mem>')
        if prod == 232:
            self.eat('$')
            self.eat('id')
        else:
            self.error_invalid_token('<mem>')

    def func(self):
        # <func>
        prod = self.get_production('<func>')
        if prod == 233:
            self.eat('(')
            self.args(_ctx_expected=(')',))
            self.eat(')')
        else:
            self.error_invalid_token('<func>')

    def args(self, _ctx_expected=()):
        # <args>
        prod = self.get_production('<args>')
        if prod == 234:
            self.value()
            self.args_mult()
        elif prod == 235:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def args_mult(self, _ctx_expected=()):
        # <args-mult>
        prod = self.get_production('<args-mult>')
        if prod == 236:
            self.eat(',')
            self.args()
        elif prod == 237:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def value(self):
        # <value>
        prod = self.get_production('<value>')
        if prod == 238:
            self.eat('id')
            self.id_tail(_ctx_expected=('!=', '%', '&', '&&', '*', '+', '-', '/', '<', '<=', '==', '>', '>=', '^', '||'))
            self.exp()
        elif prod == 239:
            self.eat('(')
            self.value()
            self.eat(')')
            self.exp()
        elif prod == 240:
            self.digit()
            self.digit_tail()
        elif prod == 241:
            self.eat('PARCH-lit')
            self.parch_tail()
        elif prod == 242:
            self.eat('SCROLL-lit')
            self.scr_char(_ctx_expected=('!=', '&', '=='))
            self.scroll_tail()
        elif prod == 243:
            self.bool()
            self.bool_eq(_ctx_expected=('&&', '||'))
            self.bool_exp()
        else:
            self.error_invalid_token('<value>')

    def digit_tail(self, _ctx_expected=()):
        # <digit-tail>
        prod = self.get_production('<digit-tail>')
        if prod == 244:
            self.var_arith(_ctx_expected=('!=', '<', '<=', '==', '>', '>='))
            self.var_releq()
        elif prod == 245:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def var_arith(self, _ctx_expected=()):
        # <var-arith>
        prod = self.get_production('<var-arith>')
        if prod == 246:
            self.arith_op()
            self.dime_ope()
            self.var_arith()
        elif prod == 247:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def var_releq(self, _ctx_expected=()):
        # <var-releq>
        prod = self.get_production('<var-releq>')
        if prod == 248:
            self.rel_op()
            self.dime_ope()
            self.bool_arith2(_ctx_expected=('!=', '&&', '==', '||'))
            self.var_logeq()
        elif prod == 249:
            self.eq_op()
            self.dime_ope()
            self.bool_arith3(_ctx_expected=('&&', '||'))
            self.bool_exp()
        elif prod == 250:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def var_logeq(self, _ctx_expected=()):
        # <var-logeq>
        prod = self.get_production('<var-logeq>')
        if prod == 251:
            self.log_op()
            self.bool_ope()
            self.bool_exp()
        elif prod == 252:
            self.eq_op()
            self.eq_ope()
            self.bool_exp()
        elif prod == 253:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_tail(self, _ctx_expected=()):
        # <parch-tail>
        prod = self.get_production('<parch-tail>')
        if prod == 254:
            self.eq_op()
            self.parch_val()
            self.bool_exp()
        elif prod == 255:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_tail(self, _ctx_expected=()):
        # <scroll-tail>
        prod = self.get_production('<scroll-tail>')
        if prod == 256:
            self.eat('&')
            self.scroll_ope()
            self.scroll_concat()
        elif prod == 257:
            self.eq_op()
            self.scroll_ope()
            self.bool_exp()
        elif prod == 258:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def exp(self, _ctx_expected=()):
        # <exp>
        prod = self.get_production('<exp>')
        if prod == 259:
            self.arith_op()
            self.dime_ope()
            self.var_arith(_ctx_expected=('!=', '<', '<=', '==', '>', '>='))
            self.var_releq()
        elif prod == 260:
            self.rel_op()
            self.dime_ope()
            self.bool_arith2(_ctx_expected=('!=', '&&', '==', '||'))
            self.var_logeq()
        elif prod == 261:
            self.log_op()
            self.bool_ope()
            self.bool_exp()
        elif prod == 262:
            self.eq_op()
            self.eq_ope()
            self.bool_exp()
        elif prod == 263:
            self.eat('&')
            self.scroll_ope()
            self.scroll_concat()
        elif prod == 264:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def const(self):
        # <const>
        prod = self.get_production('<const>')
        if prod == 265:
            self.eat('LOCKE')
            self.const_init()
            self.eat('!!')
        else:
            self.error_invalid_token('<const>')

    def const_init(self):
        # <const-init>
        prod = self.get_production('<const-init>')
        if prod == 266:
            self.eat('COIN')
            self.coin_locke()
            self.coin_locke_mult()
        elif prod == 267:
            self.eat('DIME')
            self.dime_locke()
            self.dime_locke_mult()
        elif prod == 268:
            self.eat('PARCH')
            self.parch_locke()
            self.parch_locke_mult()
        elif prod == 269:
            self.eat('SCROLL')
            self.scroll_locke()
            self.scroll_locke_mult()
        elif prod == 270:
            self.eat('BOOL')
            self.bool_locke()
            self.bool_locke_mult()
        else:
            self.error_invalid_token('<const-init>')

    def coin_locke(self):
        # <coin-locke>
        prod = self.get_production('<coin-locke>')
        if prod == 271:
            self.eat('id')
            self.eat('=')
            self.eat('COIN-lit')
        else:
            self.error_invalid_token('<coin-locke>')

    def coin_locke_mult(self, _ctx_expected=()):
        # <coin-locke-mult>
        prod = self.get_production('<coin-locke-mult>')
        if prod == 272:
            self.eat(',')
            self.coin_locke()
            self.coin_locke_mult()
        elif prod == 273:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def dime_locke(self):
        # <dime-locke>
        prod = self.get_production('<dime-locke>')
        if prod == 274:
            self.eat('id')
            self.eat('=')
            self.locke_digit()
        else:
            self.error_invalid_token('<dime-locke>')

    def locke_digit(self):
        # <locke-digit>
        prod = self.get_production('<locke-digit>')
        if prod == 275:
            self.eat('COIN-lit')
        elif prod == 276:
            self.eat('DIME-lit')
        else:
            self.error_invalid_token('<locke-digit>')

    def dime_locke_mult(self, _ctx_expected=()):
        # <dime-locke-mult>
        prod = self.get_production('<dime-locke-mult>')
        if prod == 277:
            self.eat(',')
            self.dime_locke()
            self.dime_locke_mult()
        elif prod == 278:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def parch_locke(self):
        # <parch-locke>
        prod = self.get_production('<parch-locke>')
        if prod == 279:
            self.eat('id')
            self.eat('=')
            self.eat('PARCH-lit')
        else:
            self.error_invalid_token('<parch-locke>')

    def parch_locke_mult(self, _ctx_expected=()):
        # <parch-locke-mult>
        prod = self.get_production('<parch-locke-mult>')
        if prod == 280:
            self.eat(',')
            self.parch_locke()
            self.parch_locke_mult()
        elif prod == 281:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_locke(self):
        # <scroll-locke>
        prod = self.get_production('<scroll-locke>')
        if prod == 282:
            self.eat('id')
            self.eat('=')
            self.eat('SCROLL-lit')
            self.scr_id()
        else:
            self.error_invalid_token('<scroll-locke>')

    def scr_id(self, _ctx_expected=()):
        # <scr-id>
        prod = self.get_production('<scr-id>')
        if prod == 283:
            self.eat('{')
            self.eat('COIN-lit')
            self.eat('}')
        elif prod == 284:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def scroll_locke_mult(self, _ctx_expected=()):
        # <scroll-locke-mult>
        prod = self.get_production('<scroll-locke-mult>')
        if prod == 285:
            self.eat(',')
            self.scroll_locke()
            self.scroll_locke_mult()
        elif prod == 286:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def bool_locke(self):
        # <bool-locke>
        prod = self.get_production('<bool-locke>')
        if prod == 287:
            self.eat('id')
            self.eat('=')
            self.locke_bool()
        else:
            self.error_invalid_token('<bool-locke>')

    def locke_bool(self):
        # <locke-bool>
        prod = self.get_production('<locke-bool>')
        if prod == 288:
            self.eat('AYE')
        elif prod == 289:
            self.eat('NAY')
        else:
            self.error_invalid_token('<locke-bool>')

    def bool_locke_mult(self, _ctx_expected=()):
        # <bool-locke-mult>
        prod = self.get_production('<bool-locke-mult>')
        if prod == 290:
            self.eat(',')
            self.bool_locke()
            self.bool_locke_mult()
        elif prod == 291:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def struct(self, _ctx_expected=()):
        # <struct>
        prod = self.get_production('<struct>')
        if prod == 292:
            self.eat('MAST')
            self.eat('id')
            self.eat('[')
            self.mem_dec()
            self.mem_dec_tail(_ctx_expected=(']',))
            self.eat(']')
            self.eat('!!')
            self.struct()
        elif prod == 293:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def mem_dec(self):
        # <mem-dec>
        prod = self.get_production('<mem-dec>')
        if prod == 294:
            self.d_type()
            self.eat('id')
            self.mem_mult(_ctx_expected=('!!',))
            self.eat('!!')
        else:
            self.error_invalid_token('<mem-dec>')

    def mem_mult(self, _ctx_expected=()):
        # <mem-mult>
        prod = self.get_production('<mem-mult>')
        if prod == 295:
            self.eat(',')
            self.eat('id')
            self.mem_mult()
        elif prod == 296:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def mem_dec_tail(self, _ctx_expected=()):
        # <mem-dec-tail>
        prod = self.get_production('<mem-dec-tail>')
        if prod == 297:
            self.mem_dec()
            self.mem_dec_tail()
        elif prod == 298:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def sub_func(self, _ctx_expected=()):
        # <sub-func>
        prod = self.get_production('<sub-func>')
        if prod == 299:
            self.return_func()
        elif prod == 300:
            self.nonreturn_func()
        elif prod == 301:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def return_func(self):
        # <return-func>
        prod = self.get_production('<return-func>')
        if prod == 302:
            self.eat('COIN')
            self.eat('id')
            self.coin_func()
        elif prod == 303:
            self.eat('DIME')
            self.eat('id')
            self.dime_func()
        elif prod == 304:
            self.eat('PARCH')
            self.eat('id')
            self.parch_func()
        elif prod == 305:
            self.eat('SCROLL')
            self.eat('id')
            self.scroll_func()
        elif prod == 306:
            self.eat('BOOL')
            self.eat('id')
            self.bool_func()
        else:
            self.error_invalid_token('<return-func>')

    def nonreturn_func(self):
        # <nonreturn-func>
        prod = self.get_production('<nonreturn-func>')
        if prod == 307:
            self.eat('ABYSS')
            self.eat('id')
            self.eat('(')
            self.params(_ctx_expected=(')',))
            self.eat(')')
            self.eat('[')
            self.ahoy_local_dec(_ctx_expected=('+#', '-#', 'ASK', 'CHART', 'ECHO', 'HAUL', 'HEAVE', 'HOIST', 'LOOK', 'id'))
            self.nonret_stmnts()
            self.nonret_back(_ctx_expected=(']',))
            self.eat(']')
            self.sub_func()
        else:
            self.error_invalid_token('<nonreturn-func>')

    def nonret_stmnts(self):
        # <nonret-stmnts>
        prod = self.get_production('<nonret-stmnts>')
        if prod == 308:
            self.nonret_stmnt()
            self.nonret_tail()
        else:
            self.error_invalid_token('<nonret-stmnts>')

    def nonret_tail(self, _ctx_expected=()):
        # <nonret-tail>
        prod = self.get_production('<nonret-tail>')
        if prod == 309:
            self.nonret_stmnts()
        elif prod == 310:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def nonret_stmnt(self):
        # <nonret-stmnt>
        prod = self.get_production('<nonret-stmnt>')
        if prod == 311:
            self.eat('id')
            self.assign_tail()
            self.eat('!!')
        elif prod == 312:
            self.eat('ASK')
            self.eat('(')
            self.eat('SCROLL-lit')
            self.eat(',')
            self.addr()
            self.eat(')')
            self.eat('!!')
        elif prod == 313:
            self.eat('ECHO')
            self.eat('(')
            self.eat('SCROLL-lit')
            self.args_mult(_ctx_expected=(')',))
            self.eat(')')
            self.eat('!!')
        elif prod == 314:
            self.eat('LOOK')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.nonret_look_tail()
        elif prod == 315:
            self.eat('CHART')
            self.eat('(')
            self.chart_cond()
            self.eat(')')
            self.eat('[')
            self.courses()
            self.course_tail(_ctx_expected=('ADRIFT', ']'))
            self.adrift_case(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 316:
            self.eat('HOIST')
            self.eat('(')
            self.hoist_init(_ctx_expected=('!!',))
            self.eat('!!')
            self.hoist_cond()
            self.eat('!!')
            self.hoist_upd()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 317:
            self.eat('HEAVE')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 318:
            self.eat('HAUL')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.eat('HEAVE')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('!!')
        elif prod == 319:
            self.unary_exp()
            self.eat('!!')
        else:
            self.error_invalid_token('<nonret-stmnt>')

    def nonret_look_tail(self, _ctx_expected=()):
        # <nonret-look-tail>
        prod = self.get_production('<nonret-look-tail>')
        if prod == 320:
            self.eat('DROPLOOK')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.ahoy_look_tail()
        elif prod == 321:
            self.eat('DROP')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 322:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def nonret_back(self, _ctx_expected=()):
        # <nonret-back>
        prod = self.get_production('<nonret-back>')
        if prod == 323:
            self.eat('BACK')
            self.eat('!!')
        elif prod == 324:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def local_dec(self, _ctx_expected=()):
        # <local-dec>
        prod = self.get_production('<local-dec>')
        if prod == 325:
            self.var_arr()
            self.eat('!!')
            self.local_dec()
        elif prod == 326:
            self.struct_dec()
        elif prod == 327:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def var_arr(self):
        # <var-arr>
        prod = self.get_production('<var-arr>')
        if prod == 328:
            self.eat('COIN')
            self.eat('id')
            self.coin_var_arr()
        elif prod == 329:
            self.eat('DIME')
            self.eat('id')
            self.dime_var_arr()
        elif prod == 330:
            self.eat('PARCH')
            self.eat('id')
            self.parch_var_arr()
        elif prod == 331:
            self.eat('SCROLL')
            self.eat('id')
            self.scroll_var_arr()
        elif prod == 332:
            self.eat('BOOL')
            self.eat('id')
            self.bool_var_arr()
        else:
            self.error_invalid_token('<var-arr>')

    def struct_dec(self, _ctx_expected=()):
        # <struct-dec>
        prod = self.get_production('<struct-dec>')
        if prod == 333:
            self.eat('MAST')
            self.eat('id')
            self.eat('id')
            self.str_dec_init(_ctx_expected=('!!',))
            self.eat('!!')
            self.struct_dec()
        elif prod == 334:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def str_dec_init(self, _ctx_expected=()):
        # <str-dec-init>
        prod = self.get_production('<str-dec-init>')
        if prod == 335:
            self.eat(',')
            self.eat('id')
            self.str_dec_tail()
        elif prod == 336:
            self.eat('=')
            self.eat('[')
            self.str_val()
            self.str_val_tail(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 337:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def str_dec_tail(self, _ctx_expected=()):
        # <str-dec-tail>
        prod = self.get_production('<str-dec-tail>')
        if prod == 338:
            self.eat(',')
            self.eat('id')
            self.str_dec_tail()
        elif prod == 339:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def str_val(self):
        # <str-val>
        prod = self.get_production('<str-val>')
        if prod == 340:
            self.value()
        elif prod == 341:
            self.eat('$')
            self.eat('id')
            self.eat('=')
            self.value()
        else:
            self.error_invalid_token('<str-val>')

    def str_val_tail(self, _ctx_expected=()):
        # <str-val-tail>
        prod = self.get_production('<str-val-tail>')
        if prod == 342:
            self.eat(',')
            self.str_val()
            self.str_val_tail()
        elif prod == 343:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def statements(self):
        # <statements>
        prod = self.get_production('<statements>')
        if prod == 344:
            self.assign_stmnt()
        elif prod == 345:
            self.ask_stmnt()
        elif prod == 346:
            self.echo_stmnt()
        elif prod == 347:
            self.look_stmnt()
        elif prod == 348:
            self.chart_stmnt()
        elif prod == 349:
            self.hoist_stmnt()
        elif prod == 350:
            self.heave_stmnt()
        elif prod == 351:
            self.haul_stmnt()
        elif prod == 352:
            self.unary_exp()
            self.eat('!!')
        else:
            self.error_invalid_token('<statements>')

    def assign_stmnt(self):
        # <assign-stmnt>
        prod = self.get_production('<assign-stmnt>')
        if prod == 353:
            self.eat('id')
            self.assign_tail()
            self.eat('!!')
        else:
            self.error_invalid_token('<assign-stmnt>')

    def assign_tail(self):
        # <assign-tail>
        prod = self.get_production('<assign-tail>')
        if prod == 354:
            self.arr_str(_ctx_expected=('%=', '*=', '+=', '-=', '/=', '=', '^='))
            self.assign_body()
        elif prod == 355:
            self.eat('(')
            self.args(_ctx_expected=(')',))
            self.eat(')')
        else:
            self.error_invalid_token('<assign-tail>')

    def arr_str(self, _ctx_expected=()):
        # <arr-str>
        prod = self.get_production('<arr-str>')
        if prod == 356:
            self.eat('{')
            self.index()
            self.eat('}')
            self.elmt2()
        elif prod == 357:
            self.eat('$')
            self.eat('id')
        elif prod == 358:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def assign_body(self):
        # <assign-body>
        prod = self.get_production('<assign-body>')
        if prod == 359:
            self.eat('=')
            self.value()
        elif prod == 360:
            self.arith_assign_op()
            self.dime_ope()
            self.dime_arith()
        else:
            self.error_invalid_token('<assign-body>')

    def arith_assign_op(self):
        # <arith-assign-op>
        prod = self.get_production('<arith-assign-op>')
        if prod == 361:
            self.eat('+=')
        elif prod == 362:
            self.eat('-=')
        elif prod == 363:
            self.eat('*=')
        elif prod == 364:
            self.eat('/=')
        elif prod == 365:
            self.eat('%=')
        elif prod == 366:
            self.eat('^=')
        else:
            self.error_invalid_token('<arith-assign-op>')

    def ask_stmnt(self):
        # <ask-stmnt>
        prod = self.get_production('<ask-stmnt>')
        if prod == 367:
            self.eat('ASK')
            self.eat('(')
            self.eat('SCROLL-lit')
            self.eat(',')
            self.addr()
            self.eat(')')
            self.eat('!!')
        else:
            self.error_invalid_token('<ask-stmnt>')

    def addr(self):
        # <addr>
        prod = self.get_production('<addr>')
        if prod == 368:
            self.eat('@')
            self.eat('id')
            self.arr_str(_ctx_expected=(',',))
            self.addr_tail()
        else:
            self.error_invalid_token('<addr>')

    def addr_tail(self, _ctx_expected=()):
        # <addr-tail>
        prod = self.get_production('<addr-tail>')
        if prod == 369:
            self.eat(',')
            self.addr()
        elif prod == 370:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def echo_stmnt(self):
        # <echo-stmnt>
        prod = self.get_production('<echo-stmnt>')
        if prod == 371:
            self.eat('ECHO')
            self.eat('(')
            self.eat('SCROLL-lit')
            self.args_mult(_ctx_expected=(')',))
            self.eat(')')
            self.eat('!!')
        else:
            self.error_invalid_token('<echo-stmnt>')

    def look_stmnt(self):
        # <look-stmnt>
        prod = self.get_production('<look-stmnt>')
        if prod == 372:
            self.eat('LOOK')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.look_tail()
        else:
            self.error_invalid_token('<look-stmnt>')

    def condition(self):
        # <condition>
        prod = self.get_production('<condition>')
        if prod == 373:
            self.bool_val()
        else:
            self.error_invalid_token('<condition>')

    def look_body(self, _ctx_expected=()):
        # <look-body>
        prod = self.get_production('<look-body>')
        if prod == 374:
            self.statements()
            self.look_body()
        elif prod == 375:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def jump_stmnt(self, _ctx_expected=()):
        # <jump-stmnt>
        prod = self.get_production('<jump-stmnt>')
        if prod == 376:
            self.eat('SAIL')
            self.eat('!!')
        elif prod == 377:
            self.eat('LAND')
            self.eat('!!')
        elif prod == 378:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def look_tail(self, _ctx_expected=()):
        # <look-tail>
        prod = self.get_production('<look-tail>')
        if prod == 379:
            self.eat('DROPLOOK')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.look_tail()
        elif prod == 380:
            self.eat('DROP')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 381:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def chart_stmnt(self):
        # <chart-stmnt>
        prod = self.get_production('<chart-stmnt>')
        if prod == 382:
            self.eat('CHART')
            self.eat('(')
            self.chart_cond()
            self.eat(')')
            self.eat('[')
            self.courses()
            self.course_tail(_ctx_expected=('ADRIFT', ']'))
            self.adrift_case(_ctx_expected=(']',))
            self.eat(']')
        else:
            self.error_invalid_token('<chart-stmnt>')

    def chart_cond(self):
        # <chart-cond>
        prod = self.get_production('<chart-cond>')
        if prod == 383:
            self.eat('id')
            self.id_tail()
        elif prod == 384:
            self.chart_const()
        else:
            self.error_invalid_token('<chart-cond>')

    def chart_const(self):
        # <chart-const>
        prod = self.get_production('<chart-const>')
        if prod == 385:
            self.eat('COIN-lit')
        elif prod == 386:
            self.eat('PARCH-lit')
        elif prod == 387:
            self.eat('SCROLL-lit')
            self.scr_id()
        else:
            self.error_invalid_token('<chart-const>')

    def courses(self):
        # <courses>
        prod = self.get_production('<courses>')
        if prod == 388:
            self.eat('COURSE')
            self.chart_const()
            self.eat(':')
            self.course_body(_ctx_expected=('LAND', 'SAIL'))
            self.course_jmp()
        else:
            self.error_invalid_token('<courses>')

    def course_body(self, _ctx_expected=()):
        # <course-body>
        prod = self.get_production('<course-body>')
        if prod == 389:
            self.statements()
            self.course_body()
        elif prod == 390:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def course_jmp(self, _ctx_expected=()):
        # <course-jmp>
        prod = self.get_production('<course-jmp>')
        if prod == 391:
            self.eat('SAIL')
            self.eat('!!')
        elif prod == 392:
            self.eat('LAND')
            self.eat('!!')
        elif prod == 393:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def course_tail(self, _ctx_expected=()):
        # <course-tail>
        prod = self.get_production('<course-tail>')
        if prod == 394:
            self.courses()
            self.course_tail()
        elif prod == 395:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def adrift_case(self, _ctx_expected=()):
        # <adrift-case>
        prod = self.get_production('<adrift-case>')
        if prod == 396:
            self.eat('ADRIFT')
            self.eat(':')
            self.adrift_body(_ctx_expected=('LAND',))
            self.eat('LAND')
            self.eat('!!')
        elif prod == 397:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def adrift_body(self, _ctx_expected=()):
        # <adrift-body>
        prod = self.get_production('<adrift-body>')
        if prod == 398:
            self.statements()
            self.adrift_body()
        elif prod == 399:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def hoist_stmnt(self):
        # <hoist-stmnt>
        prod = self.get_production('<hoist-stmnt>')
        if prod == 400:
            self.eat('HOIST')
            self.eat('(')
            self.hoist_init(_ctx_expected=('!!',))
            self.eat('!!')
            self.hoist_cond()
            self.eat('!!')
            self.hoist_upd()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        else:
            self.error_invalid_token('<hoist-stmnt>')

    def hoist_init(self, _ctx_expected=()):
        # <hoist-init>
        prod = self.get_production('<hoist-init>')
        if prod == 401:
            self.eat('COIN')
            self.eat('id')
            self.eat('=')
            self.eat('COIN-lit')
            self.init1_mult()
        elif prod == 402:
            self.eat('id')
            self.arr_str(_ctx_expected=('=',))
            self.eat('=')
            self.eat('COIN-lit')
            self.init2_mult()
        elif prod == 403:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def init1_mult(self, _ctx_expected=()):
        # <init1-mult>
        prod = self.get_production('<init1-mult>')
        if prod == 404:
            self.eat(',')
            self.eat('id')
            self.eat('=')
            self.eat('COIN-lit')
            self.init1_mult()
        elif prod == 405:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def init2_mult(self, _ctx_expected=()):
        # <init2-mult>
        prod = self.get_production('<init2-mult>')
        if prod == 406:
            self.eat(',')
            self.eat('id')
            self.arr_str(_ctx_expected=('=',))
            self.eat('=')
            self.eat('COIN-lit')
            self.init2_mult()
        elif prod == 407:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def hoist_cond(self):
        # <hoist-cond>
        prod = self.get_production('<hoist-cond>')
        if prod == 408:
            self.dime_ope()
            self.bool_arith(_ctx_expected=('!=', '<', '<=', '==', '>', '>='))
            self.releq_op()
            self.dime_ope()
            self.bool_arith3(_ctx_expected=('&&', '||'))
            self.hoist_log()
        else:
            self.error_invalid_token('<hoist-cond>')

    def releq_op(self):
        # <releq-op>
        prod = self.get_production('<releq-op>')
        if prod == 409:
            self.rel_op()
        elif prod == 410:
            self.eq_op()
        else:
            self.error_invalid_token('<releq-op>')

    def hoist_log(self, _ctx_expected=()):
        # <hoist-log>
        prod = self.get_production('<hoist-log>')
        if prod == 411:
            self.log_op()
            self.hoist_cond()
        elif prod == 412:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def hoist_upd(self):
        # <hoist-upd>
        prod = self.get_production('<hoist-upd>')
        if prod == 413:
            self.upd()
            self.upd_mult()
        else:
            self.error_invalid_token('<hoist-upd>')

    def upd(self):
        # <upd>
        prod = self.get_production('<upd>')
        if prod == 414:
            self.hoist_unary()
        elif prod == 415:
            self.hoist_assign()
        else:
            self.error_invalid_token('<upd>')

    def hoist_unary(self):
        # <hoist-unary>
        prod = self.get_production('<hoist-unary>')
        if prod == 416:
            self.unary_op()
            self.eat('id')
            self.arr_str()
        else:
            self.error_invalid_token('<hoist-unary>')

    def hoist_assign(self):
        # <hoist-assign>
        prod = self.get_production('<hoist-assign>')
        if prod == 417:
            self.eat('id')
            self.arr_str(_ctx_expected=('%=', '*=', '+=', '-=', '/=', '^='))
            self.arith_assign_op()
            self.coin_ope()
            self.coin_arith()
        else:
            self.error_invalid_token('<hoist-assign>')

    def upd_mult(self, _ctx_expected=()):
        # <upd-mult>
        prod = self.get_production('<upd-mult>')
        if prod == 418:
            self.eat(',')
            self.upd()
            self.upd_mult()
        elif prod == 419:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def heave_stmnt(self):
        # <heave-stmnt>
        prod = self.get_production('<heave-stmnt>')
        if prod == 420:
            self.eat('HEAVE')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        else:
            self.error_invalid_token('<heave-stmnt>')

    def haul_stmnt(self):
        # <haul-stmnt>
        prod = self.get_production('<haul-stmnt>')
        if prod == 421:
            self.eat('HAUL')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.eat('HEAVE')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('!!')
        else:
            self.error_invalid_token('<haul-stmnt>')

    def unary_exp(self):
        # <unary-exp>
        prod = self.get_production('<unary-exp>')
        if prod == 422:
            self.unary_op()
            self.eat('id')
            self.arr_str()
        else:
            self.error_invalid_token('<unary-exp>')

    def unary_op(self):
        # <unary-op>
        prod = self.get_production('<unary-op>')
        if prod == 423:
            self.eat('+#')
        elif prod == 424:
            self.eat('-#')
        else:
            self.error_invalid_token('<unary-op>')

    def ahoy_local_dec(self, _ctx_expected=()):
        # <ahoy-local-dec>
        prod = self.get_production('<ahoy-local-dec>')
        if prod == 425:
            self.var_arr()
            self.eat('!!')
            self.ahoy_local_dec()
        elif prod == 426:
            self.ahoy_struct_dec()
        elif prod == 427:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def ahoy_struct_dec(self, _ctx_expected=()):
        # <ahoy-struct-dec>
        prod = self.get_production('<ahoy-struct-dec>')
        if prod == 428:
            self.eat('MAST')
            self.eat('id')
            self.eat('id')
            self.str_dec_init(_ctx_expected=('!!',))
            self.eat('!!')
            self.ahoy_struct_dec()
        elif prod == 429:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def ahoy_stmnts(self):
        # <ahoy-stmnts>
        prod = self.get_production('<ahoy-stmnts>')
        if prod == 430:
            self.ahoy_stmnt()
            self.ahoy_tail()
        else:
            self.error_invalid_token('<ahoy-stmnts>')

    def ahoy_tail(self, _ctx_expected=()):
        # <ahoy-tail>
        prod = self.get_production('<ahoy-tail>')
        if prod == 431:
            self.ahoy_stmnts()
        elif prod == 432:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)

    def ahoy_stmnt(self):
        # <ahoy-stmnt>
        prod = self.get_production('<ahoy-stmnt>')
        if prod == 433:
            self.eat('id')
            self.assign_tail()
            self.eat('!!')
        elif prod == 434:
            self.eat('ASK')
            self.eat('(')
            self.eat('SCROLL-lit')
            self.eat(',')
            self.addr()
            self.eat(')')
            self.eat('!!')
        elif prod == 435:
            self.eat('ECHO')
            self.eat('(')
            self.eat('SCROLL-lit')
            self.args_mult(_ctx_expected=(')',))
            self.eat(')')
            self.eat('!!')
        elif prod == 436:
            self.eat('LOOK')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.ahoy_look_tail()
        elif prod == 437:
            self.eat('CHART')
            self.eat('(')
            self.chart_cond()
            self.eat(')')
            self.eat('[')
            self.courses()
            self.course_tail(_ctx_expected=('ADRIFT', ']'))
            self.adrift_case(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 438:
            self.eat('HOIST')
            self.eat('(')
            self.hoist_init(_ctx_expected=('!!',))
            self.eat('!!')
            self.hoist_cond()
            self.eat('!!')
            self.hoist_upd()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 439:
            self.eat('HEAVE')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 440:
            self.eat('HAUL')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.eat('HEAVE')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('!!')
        elif prod == 441:
            self.unary_exp()
            self.eat('!!')
        else:
            self.error_invalid_token('<ahoy-stmnt>')

    def ahoy_look_tail(self, _ctx_expected=()):
        # <ahoy-look-tail>
        prod = self.get_production('<ahoy-look-tail>')
        if prod == 442:
            self.eat('DROPLOOK')
            self.eat('(')
            self.condition()
            self.eat(')')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
            self.ahoy_look_tail()
        elif prod == 443:
            self.eat('DROP')
            self.eat('[')
            self.look_body(_ctx_expected=('LAND', 'SAIL', ']'))
            self.jump_stmnt(_ctx_expected=(']',))
            self.eat(']')
        elif prod == 444:
            pass  # Lambda
        else:
            if _ctx_expected:
                self.error_invalid_token_ctx(_ctx_expected)
            # else: no following context — silent lambda (Blind Lambda Trick)
